[feat] Project Refactor

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -62,6 +62,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build-and-push
+    environment: DEV
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -84,8 +85,8 @@ jobs:
           echo "KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}" >> .env
           echo "MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }}" >> .env
           
-          echo "PUBLIC_HOSTNAME=${{ secrets.AZURE_VM_HOST }}" >> .env
-          echo "KEYCLOAK_EXTERNAL_URL=http://${{ secrets.AZURE_VM_HOST }}:8081" >> .env
+          echo "PUBLIC_HOSTNAME=${{ secrets.PUBLIC_HOSTNAME_URL }}" >> .env
+          echo "KEYCLOAK_EXTERNAL_URL=http://${{ secrets.PUBLIC_HOSTNAME_URL }}:8081" >> .env
           echo "GITHUB_REPOSITORY_LOWER=${{ env.REPO }}" >> .env
 
 
@@ -104,17 +105,25 @@ jobs:
           host: ${{ secrets.AZURE_VM_HOST }}
           username: ${{ secrets.AZURE_VM_USERNAME }}
           password: ${{ secrets.AZURE_VM_PASSWORD }}
+          command_timeout: 60m
           script: |
             cd ~/water_dp
             
             # Login to GHCR to pull private images
             echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
             
-            # Reset environment (Delete volumes)
-            docker-compose -f docker-compose.prod.yml down -v
+            # Reset environment (Stop containers and remove volumes)
+            # "|| true" ensures this doesn't fail if containers are already down/missing
+            docker-compose -f docker-compose.prod.yml down -v || true
             
-            # Pull latest images
-            docker-compose -f docker-compose.prod.yml pull
+            # FREE DISK SPACE (Critical for small VMs)
+            # Remove all unused images, containers, networks
+            docker system prune -af
+            # Remove all unused volumes
+            docker volume prune -f
+            
+            # Pull latest images (Quietly to avoid log spam)
+            docker-compose -f docker-compose.prod.yml pull --quiet
             
             # Start services
             docker-compose -f docker-compose.prod.yml up -d
